[package]
name = "tree-sitter-formatter"
version = "0.1.0"
edition = "2021"

[dependencies]
# For the prototype we just load the json tree-sitter, eventually we will want
# to dynamically load the parser libraries, like helix.
tree-sitter-json = "0.19"
tree-sitter = "0.20"
pretty = "0.11"
