[package]
name = "tree-sitter-formatter"
description = "Takes a source file from stdin and outputs a version to stdout that is formatted according to the specified language."
version = "0.1.0"
edition = "2021"

[dependencies]
# For now we just load the tree-sitter language parsers statically. 
# Eventually we will want to dynamically load them, like Helix does.
clap = { version = "3.2.17", features = ["derive"]}
env_logger = "0.9.0"
itertools = "0.10.3"
log = "0.4.17"
pretty = "0.11"
test-log = "0.2.11"
tree-sitter = "0.20"
tree-sitter-json = "0.19"
tree-sitter-rust = "0.20.1"

[dev-dependencies]
pretty_assertions = "1.3.0"
