[package]
name = "tree-sitter-formatter"
description = "Takes a source file from stdin and outputs a version to stdout that is formatted according to the specified language."
version = "0.1.0"
edition = "2021"

[dependencies]
# For now we just load the tree-sitter language parsers statically. 
# Eventually we will want to dynamically load them, like Helix does.
clap = { version = "3.2.17", features = ["derive"]}
pretty = "0.11"
tree-sitter = "0.20"
tree-sitter-json = "0.19"
tree-sitter-rust = "0.20.1"
