[package]
name = "tree-sitter-formatter"
description = "Takes a source file from stdin and outputs a version to stdout that is formatted according to the specified language."
version = "0.1.0"
edition = "2021"

[dependencies]
# For the prototype we just load the json tree-sitter, eventually we will want
# to dynamically load the parser libraries, like helix.
tree-sitter-json = "0.19"
tree-sitter = "0.20"
pretty = "0.11"
clap = { version = "3.2.17", features = ["derive"]}
