on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Set up Nix cache
        uses: cachix/cachix-action@v10
        with:
          name: tweag-tree-sitter-formatter
          authToken: "${{ secrets.CACHIX_TWEAG_TREE_SITTER_FORMATTER_AUTH_TOKEN }}"

      - name: Build, test, and benchmark
        run: nix build -L
